In [39]:
import tensorflow as tf
import os
import pandas as pd
import numpy as np

In [40]:
model_dir = './models'

In [41]:
dataset = pd.read_csv('titanic.csv')

X = dataset[0:443][['Pclass', 'Sex', 'Age', 'Siblings/Spouses Aboard', 'Parents/Children Aboard']]
y = dataset[443:886]['Survived']

X = X.replace({'male': 0, 'female': 1})

C:\Users\felip\AppData\Local\Temp\ipykernel_12484\3264913017.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X = X.replace({'male': 0, 'female': 1})


In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [43]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, MaxAbsScaler, PowerTransformer

modelsDir = os.listdir(model_dir)

algs = [MaxAbsScaler, MinMaxScaler, PowerTransformer, RobustScaler, StandardScaler]

def runModel(alg, path):

    scaler = alg()

    X_train_normalized = scaler.fit_transform(X_train)

    model = tf.keras.Sequential([
        tf.keras.layers.Embedding(10000, 16),
        tf.keras.layers.GlobalAveragePooling1D(),
        tf.keras.layers.Dense(16, activation='relu', input_shape=(X_train_normalized.shape[1],)),
        tf.keras.layers.Dense(1, activation='sigmoid')])

    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    
    model_path = os.path.join(model_dir, path)

    model.load_weights(model_path)

    print(f"\nPesos carregados com sucesso de: {model_path}\n")

    return model

In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

from time import sleep

for i in range(len(modelsDir)):
    model = runModel(algs[i], modelsDir[i])

    y_pred = model.predict(X_test)
    y_pred_classes = np.argmax(y_pred, axis=1)

    y_true = y_test
    acc = accuracy_score(y_true, y_pred_classes)
    f1 = f1_score(y_true, y_pred_classes, average='weighted')

    print(f"\nAcurácia no conjunto de teste: {(acc*100):.2f}%")
    print(f"F1 Score no conjunto de teste: {(f1*100):.2f}%")

    # Matriz Confusão
    conf_matrix = confusion_matrix(y_true, y_pred_classes)
    print("\nMatriz de Confusão:")
    print(f'{conf_matrix}\n\n')

    sleep(1)

    

c:\Users\felip\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
c:\Users\felip\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\saving\saving_lib.py:719: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 0 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))



Pesos carregados com sucesso de: ./models\melhor_modelo_pesos_MaxAbsScaler.weights.h5

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step  

Acurácia no conjunto de teste: 62.41%
F1 Score no conjunto de teste: 47.96%

Matriz de Confusão:
[[83  0]
 [50  0]]



Pesos carregados com sucesso de: ./models\melhor_modelo_pesos_MinMaxScaler.weights.h5

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step  


c:\Users\felip\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
c:\Users\felip\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\saving\saving_lib.py:719: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 0 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))



Acurácia no conjunto de teste: 62.41%
F1 Score no conjunto de teste: 47.96%

Matriz de Confusão:
[[83  0]
 [50  0]]



Pesos carregados com sucesso de: ./models\melhor_modelo_pesos_PowerTransformer.weights.h5

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step

c:\Users\felip\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
c:\Users\felip\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\saving\saving_lib.py:719: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 0 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step 

Acurácia no conjunto de teste: 62.41%
F1 Score no conjunto de teste: 47.96%

Matriz de Confusão:
[[83  0]
 [50  0]]



Pesos carregados com sucesso de: ./models\melhor_modelo_pesos_RobustScaler.weights.h5

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

c:\Users\felip\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
c:\Users\felip\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\saving\saving_lib.py:719: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 0 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step  

Acurácia no conjunto de teste: 62.41%
F1 Score no conjunto de teste: 47.96%

Matriz de Confusão:
[[83  0]
 [50  0]]



Pesos carregados com sucesso de: ./models\melhor_modelo_pesos_StandardScaler.weights.h5

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step

c:\Users\felip\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
c:\Users\felip\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\saving\saving_lib.py:719: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 0 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step  

Acurácia no conjunto de teste: 62.41%
F1 Score no conjunto de teste: 47.96%

Matriz de Confusão:
[[83  0]
 [50  0]]


